version: '3'

services:
  shlink:
    image: shlinkio/shlink:${VERSION-stable}
    env_file: env/shlink.env
    restart: always
    depends_on:
      - redis
    ports:
      - 8080/tcp
    networks:
      - default
      - traefik_public
    labels:
      - traefik.enable=true
      - traefik.http.routers.shlink.rule=Host(`doma.in`)
      - traefik.http.services.shlink.loadbalancer.server.port=8080
      - traefik.docker.network=traefik_public

  redis:
    image: redis:5.0-alpine
    env_file: env/redis.env
    restart: always
    volumes:
    - shlink-redis-data:/data

volumes:
  shlink-redis-data:
    driver: local

networks:
  traefik_public:
    external: true
